### PR TITLE
Start using artifacts from config.yaml

### PR DESCRIPTION
**Pull request by ravanelli**

### CODE REVIEW

**Comment by travier** [comment]
Thanks. I'd prefer we don't use complex YAML semantics even if it means that we are a bit verbose. That would also avoid downloading a binary during the build. If we really need yq, it should be part of cosa.

Independent of the yq binary, from previous discussions, the idea was to move the base line of artifacts that are always built directly in the pipeline code and only keep in the config the new ones, that we can trim from time to time as releases go EOL and artifacts are built by default. (edited) 

Thus we don't need to reduce the verbosity of the list here, but in the pipeline code instead. We can start verbose.

And last, I'd prefer we keep the yaml really simple/explicit to avoid errors.

**Comment by ravanelli** [comment]
Ok, make sense! Fixed it.

**Comment by travier** [comment]
LGTM, you can push it

**Comment by ravanelli** [comment]
Closing this. I will rebase `rhcos`  branch since the logic was added in the `upstream` FCOS

**Pull request closed without merging**
